name: forest3d
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=2.3.2
  - geopandas=0.4.0
  - ipyvolume=0.5.1
  - ipywidgets=7.4.2
  - jupyter=1.0.0
  - matplotlib=3.0.2
  - numpy=1.15.4
  - pandas=0.23.4
  - pdal=1.8.0
  - plotly=3.4.2
  - python=3.6
  - python-pdal=2.1.8
  - rasterio=1.0.10
  - seaborn=0.9.0
  - pip:
    - plyfile==0.6
prefix: /home/ddiaz/anaconda3/envs/forest3d
